name: translator
version: 0.1.0
description: A free and unlimited Google Translate API for Dart. You can use it for translate strings and text for educational purpose.
author: Gabriel N. Pacheco <gabrielpacheco23@live.com>
homepage: https://github.com/gabrielpacheco23/google-translator
dependencies:
  http: ^0.11.3+17

dev_dependencies:
  test: any

environment:
    sdk: "2.0.0"